class DummyDb {
  static const List PostList = [
    {
      "proPic": "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "poornima R Nair",
      "stage": "1st",
      "position": "Full stack Developer",
      "time": "6h",
      "posting": "https://images.pexels.com/photos/19859148/pexels-photo-19859148/free-photo-of-wild-roes-in-forest.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "12 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/5586512/pexels-photo-5586512.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "John Doe",
      "stage": "2nd",
      "position": "Software Engineer",
      "time": "4h",
      "posting": "https://images.pexels.com/photos/5077039/pexels-photo-5077039.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "8 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/5585857/pexels-photo-5585857.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Jane Smith",
      "stage": "3rd",
      "position": "Web Developer",
      "time": "2h",
      "posting": "https://images.pexels.com/photos/7603052/pexels-photo-7603052.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "5 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/1925482/pexels-photo-1925482.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Alice Johnson",
      "stage": "4th",
      "position": "Data Scientist",
      "time": "1h",
      "posting": "https://images.pexels.com/photos/3550651/pexels-photo-3550651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "3 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/7431937/pexels-photo-7431937.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Bob Brown",
      "stage": "5th",
      "position": "UI/UX Designer",
      "time": "3h",
      "posting": "https://images.pexels.com/photos/4963060/pexels-photo-4963060.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "10 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/1524123/pexels-photo-1524123.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Ella Davis",
      "stage": "6th",
      "position": "Mobile Developer",
      "time": "5h",
      "posting": "https://images.pexels.com/photos/4959936/pexels-photo-4959936.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "7 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/3699259/pexels-photo-3699259.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Sam Wilson",
      "stage": "7th",
      "position": "DevOps Engineer",
      "time": "2h",
      "posting": "https://images.pexels.com/photos/8472495/pexels-photo-8472495.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "comments": "6 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/3817653/pexels-photo-3817653.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Grace Lee",
      "stage": "8th",
      "position": "Backend Developer",
      "time": "4h",
      "posting": "https://images.pexels.com/photos/3781899/pexels-photo-3781899.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "comments": "9 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/5865862/pexels-photo-5865862.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Max Anderson",
      "stage": "9th",
      "position": "Systems Analyst",
      "time": "6h",
      "posting": "https://images.pexels.com/photos/374897/pexels-photo-374897.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "11 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
    {
      "proPic": "https://images.pexels.com/photos/1549283/pexels-photo-1549283.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "username": "Olivia Garcia",
      "stage": "10th",
      "position": "Frontend Developer",
      "time": "7h",
      "posting": "https://images.pexels.com/photos/4061540/pexels-photo-4061540.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "comments": "15 comments",
      "text":"Exciting news! Our team at [Company Name] has just launched [Product/Service Name], a revolutionary solution that will transform the way you [describe the benefit.",
    },
  ];
}
